[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
paywall_program = "CPJDdpZghwWb23bgSkW5PN3PD5hPDiTcZBBVdrYwFcAy"

[programs.mainnet]
paywall_program = "prge4tp2p2R6DyYXtkyRCHJbarSAaMzEgk9u7yRFHJh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[provider.devnet]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[provider.mainnet]
cluster = "Mainnet"
wallet = "/Users/arkansio/Projects/paywall.now/token/cdiXFwFMXa6soiwcY7EC961v2BBSjREhm1cfyANPgNS.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"